# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(805, 631)
        main_window.setMinimumSize(QtCore.QSize(805, 631))
        main_window.setMaximumSize(QtCore.QSize(805, 631))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../GitHub/CMSC-447---Pinguin---UMBC/Application/GUI/Images/447logoicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        main_window.setStyleSheet("QMainWindow#main_window{\n"
"border:0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background-color:rgb(100,100,100);\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setGeometry(QtCore.QRect(0, 0, 808, 611))
        self.tab_widget.setStyleSheet("QTabWidget::pane {\n"
"  top:-1px; \n"
"  background: rgb(245, 245, 245);\n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(191, 191, 191);\n"
"  color:black\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"  }")
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tab_widget.setMovable(True)
        self.tab_widget.setObjectName("tab_widget")
        self.groups_tab = QtWidgets.QWidget()
        self.groups_tab.setStyleSheet("QWidget#groups_tab{\n"
"background-color: rgb(100,100,100);\n"
"\n"
"}")
        self.groups_tab.setObjectName("groups_tab")
        self.group_name_edit = QtWidgets.QLineEdit(self.groups_tab)
        self.group_name_edit.setGeometry(QtCore.QRect(250, 40, 301, 22))
        self.group_name_edit.setMinimumSize(QtCore.QSize(301, 22))
        self.group_name_edit.setMaximumSize(QtCore.QSize(301, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.group_name_edit.setFont(font)
        self.group_name_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.group_name_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.group_name_edit.setObjectName("group_name_edit")
        self.group_description_edit = QtWidgets.QPlainTextEdit(self.groups_tab)
        self.group_description_edit.setGeometry(QtCore.QRect(250, 70, 301, 71))
        self.group_description_edit.setMinimumSize(QtCore.QSize(301, 71))
        self.group_description_edit.setMaximumSize(QtCore.QSize(301, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.group_description_edit.setFont(font)
        self.group_description_edit.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(255,255,255);\n"
"}")
        self.group_description_edit.setObjectName("group_description_edit")
        self.invites_list = QtWidgets.QListWidget(self.groups_tab)
        self.invites_list.setGeometry(QtCore.QRect(610, 40, 181, 451))
        self.invites_list.setStyleSheet("QWidget#invites_list{\n"
"background-color: rgb(75,75,75);\n"
"border-radius:5px;\n"
"border:0px;\n"
"color:white\n"
"}")
        self.invites_list.setObjectName("invites_list")
        self.group_description_view = QtWidgets.QPlainTextEdit(self.groups_tab)
        self.group_description_view.setGeometry(QtCore.QRect(250, 320, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.group_description_view.setFont(font)
        self.group_description_view.setStyleSheet("QWidget#group_description_view{\n"
"background-color: rgb(75,75,75);\n"
"border-radius:5px;\n"
"border:0px;\n"
"color:white\n"
"}")
        self.group_description_view.setReadOnly(True)
        self.group_description_view.setObjectName("group_description_view")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groups_tab)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(610, 490, 181, 81))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.accept_invite_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.accept_invite_button.setFont(font)
        self.accept_invite_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.accept_invite_button.setObjectName("accept_invite_button")
        self.horizontalLayout_10.addWidget(self.accept_invite_button)
        self.decline_invite_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.decline_invite_button.setFont(font)
        self.decline_invite_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.decline_invite_button.setObjectName("decline_invite_button")
        self.horizontalLayout_10.addWidget(self.decline_invite_button)
        self.group_tree_label = QtWidgets.QLabel(self.groups_tab)
        self.group_tree_label.setGeometry(QtCore.QRect(15, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.group_tree_label.setFont(font)
        self.group_tree_label.setAlignment(QtCore.Qt.AlignCenter)
        self.group_tree_label.setObjectName("group_tree_label")
        self.invites_label = QtWidgets.QLabel(self.groups_tab)
        self.invites_label.setGeometry(QtCore.QRect(610, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.invites_label.setFont(font)
        self.invites_label.setAlignment(QtCore.Qt.AlignCenter)
        self.invites_label.setObjectName("invites_label")
        self.create_group_label = QtWidgets.QLabel(self.groups_tab)
        self.create_group_label.setGeometry(QtCore.QRect(250, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.create_group_label.setFont(font)
        self.create_group_label.setAlignment(QtCore.Qt.AlignCenter)
        self.create_group_label.setObjectName("create_group_label")
        self.email_edit = QtWidgets.QPlainTextEdit(self.groups_tab)
        self.email_edit.setGeometry(QtCore.QRect(250, 150, 301, 71))
        self.email_edit.setMinimumSize(QtCore.QSize(301, 71))
        self.email_edit.setMaximumSize(QtCore.QSize(301, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_edit.setFont(font)
        self.email_edit.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(255,255,255);\n"
"}")
        self.email_edit.setObjectName("email_edit")
        self.group_description_label = QtWidgets.QLabel(self.groups_tab)
        self.group_description_label.setGeometry(QtCore.QRect(250, 290, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.group_description_label.setFont(font)
        self.group_description_label.setAlignment(QtCore.Qt.AlignCenter)
        self.group_description_label.setObjectName("group_description_label")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.groups_tab)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(250, 220, 301, 41))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.create_group_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.create_group_button.setMinimumSize(QtCore.QSize(87, 24))
        self.create_group_button.setMaximumSize(QtCore.QSize(87, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_group_button.setFont(font)
        self.create_group_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.create_group_button.setObjectName("create_group_button")
        self.horizontalLayout_12.addWidget(self.create_group_button)
        self.group_bar = QtWidgets.QFrame(self.groups_tab)
        self.group_bar.setEnabled(True)
        self.group_bar.setGeometry(QtCore.QRect(0, 0, 801, 44))
        self.group_bar.setMinimumSize(QtCore.QSize(801, 44))
        self.group_bar.setMaximumSize(QtCore.QSize(801, 81))
        self.group_bar.setStyleSheet("")
        self.group_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.group_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.group_bar.setObjectName("group_bar")
        self.groups_error_frame = QtWidgets.QFrame(self.group_bar)
        self.groups_error_frame.setGeometry(QtCore.QRect(0, 0, 801, 44))
        self.groups_error_frame.setMinimumSize(QtCore.QSize(801, 44))
        self.groups_error_frame.setMaximumSize(QtCore.QSize(801, 44))
        self.groups_error_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 189, 83);\n"
"border-radius: 15px;\n"
"\n"
"}\n"
"")
        self.groups_error_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groups_error_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groups_error_frame.setObjectName("groups_error_frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groups_error_frame)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.groups_error_label = QtWidgets.QLabel(self.groups_error_frame)
        self.groups_error_label.setMinimumSize(QtCore.QSize(755, 24))
        self.groups_error_label.setMaximumSize(QtCore.QSize(755, 24))
        self.groups_error_label.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 189, 83);\n"
"border-radius:5px;\n"
"}")
        self.groups_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.groups_error_label.setObjectName("groups_error_label")
        self.horizontalLayout_18.addWidget(self.groups_error_label)
        self.groups_close_popup_button = QtWidgets.QPushButton(self.groups_error_frame)
        self.groups_close_popup_button.setMinimumSize(QtCore.QSize(20, 20))
        self.groups_close_popup_button.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groups_close_popup_button.setFont(font)
        self.groups_close_popup_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(255, 189, 83);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.groups_close_popup_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../GitHub/CMSC-447---Pinguin---UMBC/Application/GUI/Images/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.groups_close_popup_button.setIcon(icon1)
        self.groups_close_popup_button.setObjectName("groups_close_popup_button")
        self.horizontalLayout_18.addWidget(self.groups_close_popup_button)
        self.groups_tree = QtWidgets.QTreeView(self.groups_tab)
        self.groups_tree.setGeometry(QtCore.QRect(10, 40, 181, 451))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groups_tree.setFont(font)
        self.groups_tree.setStyleSheet("QWidget#groups_tree{\n"
"background-color: rgb(75,75,75);\n"
"border-radius:5px;\n"
"border:0px;\n"
"color:white\n"
"}")
        self.groups_tree.setObjectName("groups_tree")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groups_tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 500, 184, 80))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.invite_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.invite_button.setMinimumSize(QtCore.QSize(87, 24))
        self.invite_button.setMaximumSize(QtCore.QSize(87, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.invite_button.setFont(font)
        self.invite_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.invite_button.setObjectName("invite_button")
        self.horizontalLayout_11.addWidget(self.invite_button)
        self.delete_group_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.delete_group_button.setMinimumSize(QtCore.QSize(87, 24))
        self.delete_group_button.setMaximumSize(QtCore.QSize(87, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_group_button.setFont(font)
        self.delete_group_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.delete_group_button.setObjectName("delete_group_button")
        self.horizontalLayout_11.addWidget(self.delete_group_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.remove_user_edit = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.remove_user_edit.setMinimumSize(QtCore.QSize(87, 24))
        self.remove_user_edit.setMaximumSize(QtCore.QSize(87, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.remove_user_edit.setFont(font)
        self.remove_user_edit.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.remove_user_edit.setObjectName("remove_user_edit")
        self.verticalLayout_5.addWidget(self.remove_user_edit, 0, QtCore.Qt.AlignHCenter)
        self.group_tree_label.raise_()
        self.invites_label.raise_()
        self.group_name_edit.raise_()
        self.group_description_edit.raise_()
        self.invites_list.raise_()
        self.group_description_view.raise_()
        self.horizontalLayoutWidget_9.raise_()
        self.create_group_label.raise_()
        self.email_edit.raise_()
        self.group_description_label.raise_()
        self.horizontalLayoutWidget_11.raise_()
        self.groups_tree.raise_()
        self.group_bar.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.tab_widget.addTab(self.groups_tab, "")
        self.forums_tab = QtWidgets.QWidget()
        self.forums_tab.setStyleSheet("QWidget#forums_tab{\n"
"background-color: rgb(100,100,100);\n"
"\n"
"}")
        self.forums_tab.setObjectName("forums_tab")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.forums_tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(200, 0, 591, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.forum_group_label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.forum_group_label.setFont(font)
        self.forum_group_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.forum_group_label.setObjectName("forum_group_label")
        self.horizontalLayout_7.addWidget(self.forum_group_label)
        self.group_in_label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.group_in_label.setFont(font)
        self.group_in_label.setObjectName("group_in_label")
        self.horizontalLayout_7.addWidget(self.group_in_label)
        self.widget = QtWidgets.QWidget(self.forums_tab)
        self.widget.setGeometry(QtCore.QRect(190, 430, 611, 151))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.message_edit = QtWidgets.QTextEdit(self.widget)
        self.message_edit.setMaximumSize(QtCore.QSize(535, 93))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.message_edit.setFont(font)
        self.message_edit.setStyleSheet("QTextEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QTextEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.message_edit.setObjectName("message_edit")
        self.horizontalLayout_13.addWidget(self.message_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.message_button = QtWidgets.QPushButton(self.widget)
        self.message_button.setMinimumSize(QtCore.QSize(91, 24))
        self.message_button.setMaximumSize(QtCore.QSize(91, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.message_button.setFont(font)
        self.message_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.message_button.setObjectName("message_button")
        self.horizontalLayout_14.addWidget(self.message_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.forum_groups_label = QtWidgets.QLabel(self.forums_tab)
        self.forum_groups_label.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.forum_groups_label.setFont(font)
        self.forum_groups_label.setAlignment(QtCore.Qt.AlignCenter)
        self.forum_groups_label.setObjectName("forum_groups_label")
        self.forum_tree = QtWidgets.QTreeView(self.forums_tab)
        self.forum_tree.setGeometry(QtCore.QRect(10, 40, 181, 451))
        self.forum_tree.setStyleSheet("QWidget#forum_tree{\n"
"background-color: rgb(75,75,75);\n"
"border-radius:5px;\n"
"border:0px;\n"
"color:white\n"
"}")
        self.forum_tree.setObjectName("forum_tree")
        self.forums_bar = QtWidgets.QFrame(self.forums_tab)
        self.forums_bar.setEnabled(True)
        self.forums_bar.setGeometry(QtCore.QRect(0, 0, 801, 44))
        self.forums_bar.setMinimumSize(QtCore.QSize(801, 44))
        self.forums_bar.setMaximumSize(QtCore.QSize(801, 44))
        self.forums_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.forums_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.forums_bar.setObjectName("forums_bar")
        self.forums_error_frame = QtWidgets.QFrame(self.forums_bar)
        self.forums_error_frame.setGeometry(QtCore.QRect(0, 0, 801, 44))
        self.forums_error_frame.setMinimumSize(QtCore.QSize(801, 44))
        self.forums_error_frame.setMaximumSize(QtCore.QSize(801, 44))
        self.forums_error_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 189, 83);\n"
"border-radius: 15px;\n"
"\n"
"}\n"
"")
        self.forums_error_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.forums_error_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.forums_error_frame.setObjectName("forums_error_frame")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.forums_error_frame)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.forums_error_label = QtWidgets.QLabel(self.forums_error_frame)
        self.forums_error_label.setMinimumSize(QtCore.QSize(755, 24))
        self.forums_error_label.setMaximumSize(QtCore.QSize(755, 24))
        self.forums_error_label.setStyleSheet("QLabel{\n"
"background-color:rgb(255, 189, 83);\n"
"border-radius:5px;\n"
"}")
        self.forums_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.forums_error_label.setObjectName("forums_error_label")
        self.horizontalLayout_19.addWidget(self.forums_error_label)
        self.forums_close_popup_button = QtWidgets.QPushButton(self.forums_error_frame)
        self.forums_close_popup_button.setMinimumSize(QtCore.QSize(20, 20))
        self.forums_close_popup_button.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.forums_close_popup_button.setFont(font)
        self.forums_close_popup_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(255, 189, 83);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.forums_close_popup_button.setText("")
        self.forums_close_popup_button.setIcon(icon1)
        self.forums_close_popup_button.setObjectName("forums_close_popup_button")
        self.horizontalLayout_19.addWidget(self.forums_close_popup_button)
        self.forum_view = QtWidgets.QListWidget(self.forums_tab)
        self.forum_view.setGeometry(QtCore.QRect(200, 40, 591, 391))
        self.forum_view.setStyleSheet("QListWidget{\n"
"background-color: rgb(150, 150, 150);\n"
"border-radius:5px;\n"
"border:0px;\n"
"color:white\n"
"}")
        self.forum_view.setObjectName("forum_view")
        self.widget_2 = QtWidgets.QWidget(self.forums_tab)
        self.widget_2.setGeometry(QtCore.QRect(10, 490, 181, 61))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.delete_post_button = QtWidgets.QPushButton(self.widget_2)
        self.delete_post_button.setMinimumSize(QtCore.QSize(91, 24))
        self.delete_post_button.setMaximumSize(QtCore.QSize(91, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_post_button.setFont(font)
        self.delete_post_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.delete_post_button.setObjectName("delete_post_button")
        self.horizontalLayout_8.addWidget(self.delete_post_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayoutWidget_6.raise_()
        self.widget.raise_()
        self.forum_groups_label.raise_()
        self.forum_tree.raise_()
        self.forum_view.raise_()
        self.forums_bar.raise_()
        self.widget_2.raise_()
        self.tab_widget.addTab(self.forums_tab, "")
        self.calendar_tab = QtWidgets.QWidget()
        self.calendar_tab.setStyleSheet("QWidget#calendar_tab{\n"
"background-color: rgb(100,100,100);\n"
"\n"
"}")
        self.calendar_tab.setObjectName("calendar_tab")
        self.today_label = QtWidgets.QLabel(self.calendar_tab)
        self.today_label.setGeometry(QtCore.QRect(410, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.today_label.setFont(font)
        self.today_label.setAlignment(QtCore.Qt.AlignCenter)
        self.today_label.setObjectName("today_label")
        self.event_name_edit = QtWidgets.QLineEdit(self.calendar_tab)
        self.event_name_edit.setGeometry(QtCore.QRect(10, 390, 371, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.event_name_edit.setFont(font)
        self.event_name_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.event_name_edit.setObjectName("event_name_edit")
        self.event_description_edit = QtWidgets.QPlainTextEdit(self.calendar_tab)
        self.event_description_edit.setGeometry(QtCore.QRect(10, 420, 371, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.event_description_edit.setFont(font)
        self.event_description_edit.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.event_description_edit.setObjectName("event_description_edit")
        self.months_label = QtWidgets.QLabel(self.calendar_tab)
        self.months_label.setGeometry(QtCore.QRect(410, 320, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.months_label.setFont(font)
        self.months_label.setAlignment(QtCore.Qt.AlignCenter)
        self.months_label.setObjectName("months_label")
        self.months_list = QtWidgets.QListWidget(self.calendar_tab)
        self.months_list.setGeometry(QtCore.QRect(410, 350, 381, 191))
        self.months_list.setStyleSheet("QWidget#months_list{\n"
"background-color: rgb(75,75,75);\n"
"border-radius:5px;\n"
"border:0px;\n"
"color:rgb(255, 255, 255);\n"
"}")
        self.months_list.setObjectName("months_list")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.calendar_tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 319, 371, 65))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.date_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.date_label.setFont(font)
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.verticalLayout_4.addWidget(self.date_label)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.date_edit = QtWidgets.QDateEdit(self.verticalLayoutWidget_3)
        self.date_edit.setMinimumSize(QtCore.QSize(91, 24))
        self.date_edit.setMaximumSize(QtCore.QSize(91, 24))
        self.date_edit.setStyleSheet("QDateEdit{\n"
"background-color:rgb(35,35,35);\n"
"color:rgb(255,255,255);\n"
"}\n"
"QDateEdit:focus{\n"
"border: 2px solid rgb(207, 138, 0);    \n"
"}\n"
"")
        self.date_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.date_edit.setObjectName("date_edit")
        self.horizontalLayout_16.addWidget(self.date_edit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.calendar_bar = QtWidgets.QFrame(self.calendar_tab)
        self.calendar_bar.setEnabled(True)
        self.calendar_bar.setGeometry(QtCore.QRect(0, 0, 801, 44))
        self.calendar_bar.setMinimumSize(QtCore.QSize(801, 44))
        self.calendar_bar.setMaximumSize(QtCore.QSize(801, 44))
        self.calendar_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.calendar_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendar_bar.setObjectName("calendar_bar")
        self.calendar_error_frame = QtWidgets.QFrame(self.calendar_bar)
        self.calendar_error_frame.setGeometry(QtCore.QRect(0, 0, 801, 44))
        self.calendar_error_frame.setMinimumSize(QtCore.QSize(801, 44))
        self.calendar_error_frame.setMaximumSize(QtCore.QSize(801, 44))
        self.calendar_error_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 189, 83);\n"
"border-radius: 15px;\n"
"\n"
"}\n"
"")
        self.calendar_error_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendar_error_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calendar_error_frame.setObjectName("calendar_error_frame")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.calendar_error_frame)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.calendar_error_label = QtWidgets.QLabel(self.calendar_error_frame)
        self.calendar_error_label.setMinimumSize(QtCore.QSize(755, 24))
        self.calendar_error_label.setMaximumSize(QtCore.QSize(755, 24))
        self.calendar_error_label.setStyleSheet("QLabel{\n"
"background-color:rgb(255, 189, 83);\n"
"border-radius:5px;\n"
"}")
        self.calendar_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.calendar_error_label.setObjectName("calendar_error_label")
        self.horizontalLayout_20.addWidget(self.calendar_error_label)
        self.calendar_close_popup_button = QtWidgets.QPushButton(self.calendar_error_frame)
        self.calendar_close_popup_button.setMinimumSize(QtCore.QSize(20, 20))
        self.calendar_close_popup_button.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.calendar_close_popup_button.setFont(font)
        self.calendar_close_popup_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(255, 189, 83);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.calendar_close_popup_button.setText("")
        self.calendar_close_popup_button.setIcon(icon1)
        self.calendar_close_popup_button.setObjectName("calendar_close_popup_button")
        self.horizontalLayout_20.addWidget(self.calendar_close_popup_button)
        self.calendar = QtWidgets.QCalendarWidget(self.calendar_tab)
        self.calendar.setGeometry(QtCore.QRect(10, 10, 371, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calendar.setFont(font)
        self.calendar.setObjectName("calendar")
        self.todays_list = QtWidgets.QPlainTextEdit(self.calendar_tab)
        self.todays_list.setGeometry(QtCore.QRect(410, 40, 381, 191))
        self.todays_list.setStyleSheet("QPlainTextEdit{\n"
"background-color: rgb(75,75,75);\n"
"border-radius:5px;\n"
"border:0px;\n"
"color:rgb(255, 255, 255);\n"
"\n"
"}")
        self.todays_list.setObjectName("todays_list")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.calendar_tab)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(409, 539, 381, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.delete_event_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.delete_event_button.setMinimumSize(QtCore.QSize(75, 24))
        self.delete_event_button.setMaximumSize(QtCore.QSize(75, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_event_button.setFont(font)
        self.delete_event_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.delete_event_button.setObjectName("delete_event_button")
        self.horizontalLayout_9.addWidget(self.delete_event_button)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.calendar_tab)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 540, 371, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.add_event_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.add_event_button.setMinimumSize(QtCore.QSize(75, 24))
        self.add_event_button.setMaximumSize(QtCore.QSize(75, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_event_button.setFont(font)
        self.add_event_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.add_event_button.setObjectName("add_event_button")
        self.horizontalLayout_15.addWidget(self.add_event_button)
        self.today_label.raise_()
        self.event_name_edit.raise_()
        self.event_description_edit.raise_()
        self.months_label.raise_()
        self.months_list.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.calendar.raise_()
        self.todays_list.raise_()
        self.horizontalLayoutWidget_7.raise_()
        self.horizontalLayoutWidget_8.raise_()
        self.calendar_bar.raise_()
        self.tab_widget.addTab(self.calendar_tab, "")
        self.tasks_tab = QtWidgets.QWidget()
        self.tasks_tab.setStyleSheet("QWidget#tasks_tab{\n"
"background-color: rgb(100,100,100);\n"
"\n"
"}")
        self.tasks_tab.setObjectName("tasks_tab")
        self.trello_tree = QtWidgets.QTreeView(self.tasks_tab)
        self.trello_tree.setGeometry(QtCore.QRect(10, 40, 181, 531))
        self.trello_tree.setStyleSheet("QWidget#trello_tree{\n"
"background-color: rgb(75,75,75);\n"
"border-radius:5px;\n"
"border:0px\n"
"}")
        self.trello_tree.setObjectName("trello_tree")
        self.line = QtWidgets.QFrame(self.tasks_tab)
        self.line.setGeometry(QtCore.QRect(200, 260, 591, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tasks_tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(360, 40, 281, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.add_list_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_list_edit.setFont(font)
        self.add_list_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.add_list_edit.setObjectName("add_list_edit")
        self.horizontalLayout_4.addWidget(self.add_list_edit, 0, QtCore.Qt.AlignLeft)
        self.add_list_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_list_button.setFont(font)
        self.add_list_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.add_list_button.setObjectName("add_list_button")
        self.horizontalLayout_4.addWidget(self.add_list_button)
        self.delete_list_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_list_button.setFont(font)
        self.delete_list_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.delete_list_button.setObjectName("delete_list_button")
        self.horizontalLayout_4.addWidget(self.delete_list_button)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tasks_tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(210, 140, 581, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.list_move_from_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_move_from_edit.setFont(font)
        self.list_move_from_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.list_move_from_edit.setObjectName("list_move_from_edit")
        self.horizontalLayout_5.addWidget(self.list_move_from_edit)
        self.card_move_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.card_move_edit.setFont(font)
        self.card_move_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.card_move_edit.setText("")
        self.card_move_edit.setObjectName("card_move_edit")
        self.horizontalLayout_5.addWidget(self.card_move_edit)
        self.list_move_to_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_move_to_edit.setFont(font)
        self.list_move_to_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.list_move_to_edit.setText("")
        self.list_move_to_edit.setObjectName("list_move_to_edit")
        self.horizontalLayout_5.addWidget(self.list_move_to_edit)
        self.move_card_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.move_card_button.setFont(font)
        self.move_card_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.move_card_button.setObjectName("move_card_button")
        self.horizontalLayout_5.addWidget(self.move_card_button)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tasks_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 320, 241, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.task_card_view = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.task_card_view.setFont(font)
        self.task_card_view.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.task_card_view.setReadOnly(True)
        self.task_card_view.setObjectName("task_card_view")
        self.verticalLayout_2.addWidget(self.task_card_view)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.edit_task_description_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edit_task_description_button.setFont(font)
        self.edit_task_description_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.edit_task_description_button.setObjectName("edit_task_description_button")
        self.horizontalLayout_6.addWidget(self.edit_task_description_button)
        self.delete_task_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_task_button.setFont(font)
        self.delete_task_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.delete_task_button.setObjectName("delete_task_button")
        self.horizontalLayout_6.addWidget(self.delete_task_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tasks_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(550, 320, 241, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.card_add_list_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.card_add_list_edit.setFont(font)
        self.card_add_list_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.card_add_list_edit.setObjectName("card_add_list_edit")
        self.verticalLayout.addWidget(self.card_add_list_edit)
        self.card_add_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.card_add_edit.setFont(font)
        self.card_add_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.card_add_edit.setObjectName("card_add_edit")
        self.verticalLayout.addWidget(self.card_add_edit)
        self.card_description_edit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.card_description_edit.setFont(font)
        self.card_description_edit.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.card_description_edit.setObjectName("card_description_edit")
        self.verticalLayout.addWidget(self.card_description_edit)
        self.card_add_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.card_add_button.setFont(font)
        self.card_add_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.card_add_button.setObjectName("card_add_button")
        self.verticalLayout.addWidget(self.card_add_button)
        self.task_card_label = QtWidgets.QLabel(self.tasks_tab)
        self.task_card_label.setGeometry(QtCore.QRect(215, 290, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.task_card_label.setFont(font)
        self.task_card_label.setAlignment(QtCore.Qt.AlignCenter)
        self.task_card_label.setObjectName("task_card_label")
        self.label_7 = QtWidgets.QLabel(self.tasks_tab)
        self.label_7.setGeometry(QtCore.QRect(545, 290, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.Tasks_Label = QtWidgets.QLabel(self.tasks_tab)
        self.Tasks_Label.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Tasks_Label.setFont(font)
        self.Tasks_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Tasks_Label.setObjectName("Tasks_Label")
        self.tasks_bar = QtWidgets.QFrame(self.tasks_tab)
        self.tasks_bar.setEnabled(True)
        self.tasks_bar.setGeometry(QtCore.QRect(0, 0, 801, 44))
        self.tasks_bar.setMinimumSize(QtCore.QSize(801, 44))
        self.tasks_bar.setMaximumSize(QtCore.QSize(801, 44))
        self.tasks_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tasks_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tasks_bar.setObjectName("tasks_bar")
        self.tasks_error_frame = QtWidgets.QFrame(self.tasks_bar)
        self.tasks_error_frame.setGeometry(QtCore.QRect(0, 0, 801, 44))
        self.tasks_error_frame.setMinimumSize(QtCore.QSize(801, 44))
        self.tasks_error_frame.setMaximumSize(QtCore.QSize(801, 44))
        self.tasks_error_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 189, 83);\n"
"border-radius: 15px;\n"
"\n"
"}\n"
"")
        self.tasks_error_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tasks_error_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tasks_error_frame.setObjectName("tasks_error_frame")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.tasks_error_frame)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.tasks_error_label = QtWidgets.QLabel(self.tasks_error_frame)
        self.tasks_error_label.setMinimumSize(QtCore.QSize(755, 24))
        self.tasks_error_label.setMaximumSize(QtCore.QSize(755, 24))
        self.tasks_error_label.setStyleSheet("QLabel{\n"
"background-color:rgb(255, 189, 83);\n"
"border-radius:5px;\n"
"}")
        self.tasks_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tasks_error_label.setObjectName("tasks_error_label")
        self.horizontalLayout_21.addWidget(self.tasks_error_label)
        self.tasks_close_popup_button = QtWidgets.QPushButton(self.tasks_error_frame)
        self.tasks_close_popup_button.setMinimumSize(QtCore.QSize(20, 20))
        self.tasks_close_popup_button.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tasks_close_popup_button.setFont(font)
        self.tasks_close_popup_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(255, 189, 83);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.tasks_close_popup_button.setText("")
        self.tasks_close_popup_button.setIcon(icon1)
        self.tasks_close_popup_button.setObjectName("tasks_close_popup_button")
        self.horizontalLayout_21.addWidget(self.tasks_close_popup_button)
        self.Tasks_Label.raise_()
        self.trello_tree.raise_()
        self.tasks_bar.raise_()
        self.line.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.horizontalLayoutWidget_5.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.task_card_label.raise_()
        self.label_7.raise_()
        self.tab_widget.addTab(self.tasks_tab, "")
        self.documents_tab = QtWidgets.QWidget()
        self.documents_tab.setStyleSheet("QWidget#documents_tab{\n"
"background-color: rgb(100,100,100);\n"
"\n"
"}")
        self.documents_tab.setObjectName("documents_tab")
        self.document_list = QtWidgets.QListWidget(self.documents_tab)
        self.document_list.setGeometry(QtCore.QRect(200, 40, 591, 211))
        self.document_list.setStyleSheet("QWidget#document_list{\n"
"background-color: rgb(75,75,75);\n"
"color: white;\n"
"border-radius:5px;\n"
"border:0px\n"
"}")
        self.document_list.setObjectName("document_list")
        self.document_label = QtWidgets.QLabel(self.documents_tab)
        self.document_label.setGeometry(QtCore.QRect(230, 10, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.document_label.setFont(font)
        self.document_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.document_label.setAlignment(QtCore.Qt.AlignCenter)
        self.document_label.setObjectName("document_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.documents_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 370, 582, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.doc_share_name_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.doc_share_name_edit.setMinimumSize(QtCore.QSize(234, 24))
        self.doc_share_name_edit.setMaximumSize(QtCore.QSize(338, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doc_share_name_edit.setFont(font)
        self.doc_share_name_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.doc_share_name_edit.setObjectName("doc_share_name_edit")
        self.horizontalLayout.addWidget(self.doc_share_name_edit)
        self.doc_share_link_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.doc_share_link_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.doc_share_link_edit.setMaximumSize(QtCore.QSize(338, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doc_share_link_edit.setFont(font)
        self.doc_share_link_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.doc_share_link_edit.setObjectName("doc_share_link_edit")
        self.horizontalLayout.addWidget(self.doc_share_link_edit)
        self.doc_share_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.doc_share_button.setMinimumSize(QtCore.QSize(100, 24))
        self.doc_share_button.setMaximumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doc_share_button.setFont(font)
        self.doc_share_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.doc_share_button.setObjectName("doc_share_button")
        self.horizontalLayout.addWidget(self.doc_share_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.documents_tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(210, 260, 581, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.doc_create_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.doc_create_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.doc_create_edit.setMaximumSize(QtCore.QSize(680, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doc_create_edit.setFont(font)
        self.doc_create_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.doc_create_edit.setObjectName("doc_create_edit")
        self.horizontalLayout_2.addWidget(self.doc_create_edit)
        self.doc_create_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.doc_create_button.setMinimumSize(QtCore.QSize(100, 24))
        self.doc_create_button.setMaximumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doc_create_button.setFont(font)
        self.doc_create_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.doc_create_button.setObjectName("doc_create_button")
        self.horizontalLayout_2.addWidget(self.doc_create_button)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.documents_tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(210, 480, 581, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.doc_delete_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.doc_delete_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.doc_delete_edit.setMaximumSize(QtCore.QSize(680, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doc_delete_edit.setFont(font)
        self.doc_delete_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.doc_delete_edit.setObjectName("doc_delete_edit")
        self.horizontalLayout_3.addWidget(self.doc_delete_edit)
        self.doc_delete_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.doc_delete_button.setMinimumSize(QtCore.QSize(100, 24))
        self.doc_delete_button.setMaximumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doc_delete_button.setFont(font)
        self.doc_delete_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.doc_delete_button.setObjectName("doc_delete_button")
        self.horizontalLayout_3.addWidget(self.doc_delete_button)
        self.docs_bar = QtWidgets.QFrame(self.documents_tab)
        self.docs_bar.setEnabled(True)
        self.docs_bar.setGeometry(QtCore.QRect(0, 0, 801, 44))
        self.docs_bar.setMinimumSize(QtCore.QSize(801, 44))
        self.docs_bar.setMaximumSize(QtCore.QSize(801, 44))
        self.docs_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.docs_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.docs_bar.setObjectName("docs_bar")
        self.docs_error_frame = QtWidgets.QFrame(self.docs_bar)
        self.docs_error_frame.setGeometry(QtCore.QRect(0, 0, 801, 44))
        self.docs_error_frame.setMinimumSize(QtCore.QSize(801, 44))
        self.docs_error_frame.setMaximumSize(QtCore.QSize(801, 44))
        self.docs_error_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 189, 83);\n"
"border-radius: 15px;\n"
"\n"
"}\n"
"")
        self.docs_error_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.docs_error_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.docs_error_frame.setObjectName("docs_error_frame")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.docs_error_frame)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.docs_error_label = QtWidgets.QLabel(self.docs_error_frame)
        self.docs_error_label.setMinimumSize(QtCore.QSize(755, 24))
        self.docs_error_label.setMaximumSize(QtCore.QSize(755, 24))
        self.docs_error_label.setStyleSheet("QLabel{\n"
"background-color:rgb(255, 189, 83);\n"
"border-radius:5px;\n"
"}")
        self.docs_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.docs_error_label.setObjectName("docs_error_label")
        self.horizontalLayout_22.addWidget(self.docs_error_label)
        self.docs_close_popup_button = QtWidgets.QPushButton(self.docs_error_frame)
        self.docs_close_popup_button.setMinimumSize(QtCore.QSize(20, 20))
        self.docs_close_popup_button.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.docs_close_popup_button.setFont(font)
        self.docs_close_popup_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(255, 189, 83);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.docs_close_popup_button.setText("")
        self.docs_close_popup_button.setIcon(icon1)
        self.docs_close_popup_button.setObjectName("docs_close_popup_button")
        self.horizontalLayout_22.addWidget(self.docs_close_popup_button)
        self.docs_tree = QtWidgets.QTreeView(self.documents_tab)
        self.docs_tree.setGeometry(QtCore.QRect(10, 40, 181, 531))
        self.docs_tree.setStyleSheet("QWidget#docs_tree{\n"
"background-color: rgb(75,75,75);\n"
"border-radius:5px;\n"
"border:0px\n"
"}")
        self.docs_tree.setObjectName("docs_tree")
        self.docs_group_label = QtWidgets.QLabel(self.documents_tab)
        self.docs_group_label.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.docs_group_label.setFont(font)
        self.docs_group_label.setAlignment(QtCore.Qt.AlignCenter)
        self.docs_group_label.setObjectName("docs_group_label")
        self.document_list.raise_()
        self.document_label.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.docs_tree.raise_()
        self.docs_group_label.raise_()
        self.docs_bar.raise_()
        self.tab_widget.addTab(self.documents_tab, "")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 22))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)

        self.retranslateUi(main_window)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "main_window"))
        self.group_name_edit.setPlaceholderText(_translate("main_window", "Name of the Group you want to create"))
        self.group_description_edit.setPlaceholderText(_translate("main_window", "Description for the Group you want to create."))
        self.invites_list.setToolTip(_translate("main_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Click on an invite, if you want to accept or decline the invitation.</span></p></body></html>"))
        self.group_description_view.setPlaceholderText(_translate("main_window", "No Group selected."))
        self.accept_invite_button.setText(_translate("main_window", "Accept"))
        self.decline_invite_button.setText(_translate("main_window", "Decline"))
        self.group_tree_label.setText(_translate("main_window", "Groups"))
        self.invites_label.setText(_translate("main_window", "Group Invites"))
        self.create_group_label.setText(_translate("main_window", "Create Group"))
        self.email_edit.setPlaceholderText(_translate("main_window", "Enter emails of invites (e.g. email1@gmail.com, email2@gmail.com). If you don\'t invite any members now, you can invite them with the \"Invite Members\" button."))
        self.group_description_label.setText(_translate("main_window", "Group Description"))
        self.create_group_button.setText(_translate("main_window", "Create Group"))
        self.groups_error_label.setText(_translate("main_window", "This is an error"))
        self.invite_button.setText(_translate("main_window", "Invite Users"))
        self.delete_group_button.setText(_translate("main_window", "Delete Group"))
        self.remove_user_edit.setText(_translate("main_window", "Remove User"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.groups_tab), _translate("main_window", "Groups"))
        self.forum_group_label.setText(_translate("main_window", "Talking in Group:"))
        self.group_in_label.setText(_translate("main_window", "Pick a group"))
        self.message_edit.setPlaceholderText(_translate("main_window", "Enter a message to send to your group members."))
        self.message_button.setText(_translate("main_window", "Send Message"))
        self.forum_groups_label.setText(_translate("main_window", "Groups"))
        self.forums_error_label.setText(_translate("main_window", "This is an error"))
        self.delete_post_button.setText(_translate("main_window", "Remove Post"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.forums_tab), _translate("main_window", "Forums"))
        self.today_label.setText(_translate("main_window", "Todays Events"))
        self.event_name_edit.setPlaceholderText(_translate("main_window", "Enter a title for your event."))
        self.event_description_edit.setPlaceholderText(_translate("main_window", "Enter a description for your event."))
        self.months_label.setText(_translate("main_window", "This Months Events"))
        self.months_list.setToolTip(_translate("main_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Click on an event to view its description.</span></p></body></html>"))
        self.date_label.setText(_translate("main_window", "Enter a Date"))
        self.date_edit.setToolTip(_translate("main_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Select a day from the calendar to change the date.</span></p></body></html>"))
        self.calendar_error_label.setText(_translate("main_window", "This is an error"))
        self.delete_event_button.setText(_translate("main_window", "Delete Event"))
        self.add_event_button.setText(_translate("main_window", "Add Event"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.calendar_tab), _translate("main_window", "Calendar"))
        self.trello_tree.setToolTip(_translate("main_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Click on task card to view its description.</span></p></body></html>"))
        self.add_list_edit.setPlaceholderText(_translate("main_window", "List Name"))
        self.add_list_button.setText(_translate("main_window", "Add List"))
        self.delete_list_button.setText(_translate("main_window", "Delete List"))
        self.list_move_from_edit.setPlaceholderText(_translate("main_window", "List(From)"))
        self.card_move_edit.setPlaceholderText(_translate("main_window", "Card"))
        self.list_move_to_edit.setPlaceholderText(_translate("main_window", "List(To)"))
        self.move_card_button.setText(_translate("main_window", "Move Card"))
        self.task_card_view.setPlaceholderText(_translate("main_window", "Pick a task card  to the left to view a description of the currently selected card. You can edit the description or delete the task card with the buttons below."))
        self.edit_task_description_button.setText(_translate("main_window", "Edit Description"))
        self.delete_task_button.setText(_translate("main_window", "Delete Task Card"))
        self.card_add_list_edit.setPlaceholderText(_translate("main_window", "List Name"))
        self.card_add_edit.setPlaceholderText(_translate("main_window", "Task Card Name"))
        self.card_description_edit.setPlaceholderText(_translate("main_window", "Enter a description for the task card."))
        self.card_add_button.setText(_translate("main_window", "Add Task Card"))
        self.task_card_label.setText(_translate("main_window", "Task Card"))
        self.label_7.setText(_translate("main_window", "Create a Task Card"))
        self.Tasks_Label.setText(_translate("main_window", "Tasks"))
        self.tasks_error_label.setText(_translate("main_window", "This is an error"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tasks_tab), _translate("main_window", "Tasks"))
        self.document_label.setText(_translate("main_window", "Document Links"))
        self.doc_share_name_edit.setPlaceholderText(_translate("main_window", "Enter a name for the link"))
        self.doc_share_link_edit.setPlaceholderText(_translate("main_window", "Enter the link"))
        self.doc_share_button.setText(_translate("main_window", "Share Link"))
        self.doc_create_edit.setPlaceholderText(_translate("main_window", "Enter a name for the Google Doc"))
        self.doc_create_button.setText(_translate("main_window", "Create Doc"))
        self.doc_delete_edit.setPlaceholderText(_translate("main_window", "Enter the name of the document you want to delete"))
        self.doc_delete_button.setText(_translate("main_window", "Delete Link"))
        self.docs_error_label.setText(_translate("main_window", "This is an error"))
        self.docs_tree.setToolTip(_translate("main_window", "<html><head/><body><p><br/></p></body></html>"))
        self.docs_group_label.setText(_translate("main_window", "Groups"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.documents_tab), _translate("main_window", "Documents"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
