# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\GitHub\CMSC-447---Pinguin---UMBC\Application\GUI\Uis\Trello_Pin_Window_Ui\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trello_pin_window(object):
    def setupUi(self, trello_pin_window):
        trello_pin_window.setObjectName("trello_pin_window")
        trello_pin_window.resize(300, 300)
        trello_pin_window.setMinimumSize(QtCore.QSize(300, 300))
        trello_pin_window.setMaximumSize(QtCore.QSize(300, 300))
        trello_pin_window.setStyleSheet("QWidget#trello_pin_window{\n"
"background-color: rgb(100,100,100);\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(trello_pin_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 120, 301, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.trello_pin_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.trello_pin_edit.setMinimumSize(QtCore.QSize(250, 22))
        self.trello_pin_edit.setMaximumSize(QtCore.QSize(250, 22))
        self.trello_pin_edit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255,255,255);\n"
"}")
        self.trello_pin_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.trello_pin_edit.setObjectName("trello_pin_edit")
        self.horizontalLayout.addWidget(self.trello_pin_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connect_trello_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.connect_trello_button.setMinimumSize(QtCore.QSize(100, 0))
        self.connect_trello_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.connect_trello_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.connect_trello_button.setObjectName("connect_trello_button")
        self.horizontalLayout_2.addWidget(self.connect_trello_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.trello_pin_label = QtWidgets.QLabel(trello_pin_window)
        self.trello_pin_label.setGeometry(QtCore.QRect(0, 80, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trello_pin_label.setFont(font)
        self.trello_pin_label.setAlignment(QtCore.Qt.AlignCenter)
        self.trello_pin_label.setObjectName("trello_pin_label")

        self.retranslateUi(trello_pin_window)
        QtCore.QMetaObject.connectSlotsByName(trello_pin_window)

    def retranslateUi(self, trello_pin_window):
        _translate = QtCore.QCoreApplication.translate
        trello_pin_window.setWindowTitle(_translate("trello_pin_window", "trello_pin_window"))
        self.trello_pin_edit.setPlaceholderText(_translate("trello_pin_window", "Enter Pin"))
        self.connect_trello_button.setText(_translate("trello_pin_window", "Connect with Trello"))
        self.trello_pin_label.setText(_translate("trello_pin_window", "Connect with Trello"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trello_pin_window = QtWidgets.QWidget()
    ui = Ui_trello_pin_window()
    ui.setupUi(trello_pin_window)
    trello_pin_window.show()
    sys.exit(app.exec_())
