# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\GitHub\CMSC-447---Pinguin---UMBC\Application\GUI\Uis\Invite_Menu_Ui\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_invites_menu(object):
    def setupUi(self, invites_menu):
        invites_menu.setObjectName("invites_menu")
        invites_menu.resize(400, 400)
        invites_menu.setMinimumSize(QtCore.QSize(400, 400))
        invites_menu.setMaximumSize(QtCore.QSize(213123, 16777215))
        invites_menu.setStyleSheet("QDialog{\n"
" background-color:rgb(100, 100, 100);}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(invites_menu)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 340, 261, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.send_invites_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.send_invites_button.setMaximumSize(QtCore.QSize(123, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.send_invites_button.setFont(font)
        self.send_invites_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.send_invites_button.setObjectName("send_invites_button")
        self.horizontalLayout.addWidget(self.send_invites_button)
        self.cancel_invites_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_invites_button.setMaximumSize(QtCore.QSize(123, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancel_invites_button.setFont(font)
        self.cancel_invites_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color:rgb(255, 170, 0);\n"
"    border: 2px solid rgb(207, 138, 0);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.cancel_invites_button.setObjectName("cancel_invites_button")
        self.horizontalLayout.addWidget(self.cancel_invites_button)
        self.verticalLayoutWidget = QtWidgets.QWidget(invites_menu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 54, 402, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(75, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.send_invites_edit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.send_invites_edit.setMinimumSize(QtCore.QSize(251, 231))
        self.send_invites_edit.setMaximumSize(QtCore.QSize(251, 231))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.send_invites_edit.setFont(font)
        self.send_invites_edit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.send_invites_edit.setStyleSheet("QPlainTextEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(255,255,255);\n"
"}\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(207, 138, 0);    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.send_invites_edit.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.send_invites_edit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.send_invites_edit.setLineWidth(1)
        self.send_invites_edit.setObjectName("send_invites_edit")
        self.verticalLayout.addWidget(self.send_invites_edit)
        self.send_invites_label = QtWidgets.QLabel(invites_menu)
        self.send_invites_label.setGeometry(QtCore.QRect(80, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.send_invites_label.setFont(font)
        self.send_invites_label.setAlignment(QtCore.Qt.AlignCenter)
        self.send_invites_label.setObjectName("send_invites_label")
        self.invites_error_frame = QtWidgets.QFrame(invites_menu)
        self.invites_error_frame.setGeometry(QtCore.QRect(0, 0, 401, 51))
        self.invites_error_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 189, 83);\n"
"border-radius: 15px;\n"
"\n"
"}\n"
"")
        self.invites_error_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.invites_error_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.invites_error_frame.setObjectName("invites_error_frame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.invites_error_frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 401, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.invites_error_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.invites_error_label.setMinimumSize(QtCore.QSize(370, 0))
        self.invites_error_label.setMaximumSize(QtCore.QSize(370, 16777215))
        self.invites_error_label.setStyleSheet("QLabel{\n"
"background-color:rgb(255, 189, 83);\n"
"border-radius:5px;\n"
"}")
        self.invites_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.invites_error_label.setObjectName("invites_error_label")
        self.horizontalLayout_2.addWidget(self.invites_error_label)
        self.invites_error_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.invites_error_button.setMinimumSize(QtCore.QSize(20, 20))
        self.invites_error_button.setMaximumSize(QtCore.QSize(20, 20))
        self.invites_error_button.setStyleSheet("QPushButton {    \n"
"    background-color: rgb(50, 50, 50);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(255, 189, 83);\n"
"    border: 2px solid rgb(255, 165, 24);    \n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.invites_error_button.setText("")
        self.invites_error_button.setObjectName("invites_error_button")
        self.horizontalLayout_2.addWidget(self.invites_error_button)

        self.retranslateUi(invites_menu)
        QtCore.QMetaObject.connectSlotsByName(invites_menu)

    def retranslateUi(self, invites_menu):
        _translate = QtCore.QCoreApplication.translate
        invites_menu.setWindowTitle(_translate("invites_menu", "invites_menu"))
        self.send_invites_button.setText(_translate("invites_menu", "Send Invites"))
        self.cancel_invites_button.setText(_translate("invites_menu", "Cancel"))
        self.send_invites_edit.setPlaceholderText(_translate("invites_menu", "email1@gmail.com, email2@gmail.com, email3@gmail.com, ..."))
        self.send_invites_label.setText(_translate("invites_menu", "Send Invites"))
        self.invites_error_label.setText(_translate("invites_menu", "This is an error"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    invites_menu = QtWidgets.QDialog()
    ui = Ui_invites_menu()
    ui.setupUi(invites_menu)
    invites_menu.show()
    sys.exit(app.exec_())
